[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black   = "#181819"
blue    = "#76CCE0"
cyan    = "#85D3F2"
green   = "#9ED072"
magenta = "#B39DF3"
red     = "#FC5D7C"
white   = "#E2E2E3"
yellow  = "#E7C664"

[colors.normal]
black   = "#181819"
blue    = "#76CCE0"
cyan    = "#85D3F2"
green   = "#9ED072"
magenta = "#B39DF3"
red     = "#FC5D7C"
white   = "#E2E2E3"
yellow  = "#E7C664"

[colors.primary]
background = "#2C2E34"
foreground = "#E2E2E3"

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 10

[font.bold]
# family = "Jetbrains Mono"
family = "0xProtoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "0xProtoNerdFontMono"
style = "BoldItalic"

[font.normal]
family = "0xProtoNerdFontMono"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

[terminal]
