theme = "sonokai"

[editor]
bufferline = "multiple" # Show buffers when more than one is open
cursorline = true # Highlight the line where the cursor is
line-number = "relative"
# rulers = [120] # Highlight the 120 char width
true-color = true # Force the theme to show colors
color-modes = true # Colors for INSERT NORMAL & SELECT
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "â•Ž"
render = true
skip-levels = 1

[editor.lsp]
display-messages = true # Show LSP messages in statusline

[editor.statusline]
# left = ["mode", "spinner", "version-control", "file-name"]
left = ["mode", "version-control", "file-modification-indicator", "spinner"]
center = ["file-name", "read-only-indicator"]
right = ["position", "separator", "total-line-numbers", "separator", "file-type"]
separator = "//"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
